name: gestao_incidentes_desktop
description: Aplicação desktop standalone para gestão de incidentes (Flutter + SQLite)
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1
  path_provider: ^2.1.5
  google_fonts: ^6.3.2
  bcrypt: ^1.1.3
  pdf: ^3.11.3
  csv: ^6.0.0
  fl_chart: ^1.1.1
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  encrypt: ^5.0.3
  logger: ^2.6.2
  argon2: ^1.0.1
  flutter_windowmanager: ^0.2.0
  ffi: ^2.1.0
  win32: ^5.2.0
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  characters: ^1.4.1
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_macos: ^4.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  flutter_secure_storage_web: ^2.0.0
  flutter_secure_storage_windows: ^4.0.0
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  pointycastle: ^4.0.0
  test_api: ^0.7.7
>>>>>>> 7fcbba4b7819467774316a6aa798808323b4d9ab

flutter:
  uses-material-design: true
  assets:
    - assets/db/gestao_incidentes.db
