name: gestao_incidentes_desktop
description: Aplicação desktop standalone para gestão de incidentes (Flutter + SQLite)
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  google_fonts: ^6.1.0
  bcrypt: ^1.1.3
  pdf: ^3.11.3
  csv: ^6.0.0
  fl_chart: ^1.1.1

    # dependências para segurança
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.1
  encrypt: ^5.0.3
  logger: ^2.5.0
  argon2: ^1.0.1
  flutter_windowmanager: ^0.2.0
  permission_handler: ^11.0.1
  ffi: ^2.1.0
  win32: ^5.2.0
  window_manager: ^0.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/db/gestao_incidentes.db
